import type { TSESLint } from '@typescript-eslint/utils';

/**
 * Workflow config - strict determinism rules for workflow files
 */
export const workflowRules: TSESLint.FlatConfig.Rules = {
  'temporal/workflow-condition-timeout-style': 'warn',
  'temporal/workflow-no-activity-definitions-import': 'error',
  'temporal/workflow-duration-format': 'warn',
  'temporal/workflow-activity-timeout-duration-format': 'warn',
  'temporal/workflow-require-message-definitions-at-module-scope': 'warn',
  'temporal/workflow-prefer-CancellationScope-withTimeout': 'warn',
  'temporal/workflow-no-settimeout-in-cancellation-scope': 'warn',
  'temporal/workflow-no-swallow-cancellation': 'warn',
  'temporal/workflow-nonCancellable-cleanup-required': 'warn',
  'temporal/workflow-await-cancelRequested-in-nonCancellable-pattern': 'warn',
  'temporal/workflow-no-await-in-handler-without-exit-guard': 'warn',
  'temporal/workflow-no-fs-in-workflow': 'error',
  'temporal/workflow-no-node-or-dom-imports': 'error',
  'temporal/workflow-no-network-in-workflow': 'error',
  'temporal/workflow-no-logger-library-in-workflow': 'error',
  'temporal/workflow-no-uuid-library-in-workflow': 'error',
  'temporal/workflow-no-mixed-scope-exports': 'error',
  'temporal/workflow-no-top-level-workflow-side-effects': 'error',
  'temporal/workflow-no-unsafe-package-imports': 'error',
  'temporal/workflow-no-nondeterministic-control-flow': 'warn',
  'temporal/workflow-no-date-now-tight-loop': 'warn',
  'temporal/workflow-no-wall-clock-assumptions': 'warn',
  'temporal/workflow-uuid4-requires-security-comment': 'warn',
  'temporal/workflow-no-heavy-cpu-in-workflow': 'warn',
  'temporal/workflow-no-large-literal-activity-payloads': 'warn',
  'temporal/workflow-no-large-literal-payloads': 'warn',
  'temporal/workflow-no-console': 'error',
  'temporal/workflow-require-activity-timeouts': 'error',
  'temporal/workflow-no-retry-for-nonidempotent-activities': 'warn',
  'temporal/workflow-require-idempotency-key-arg': 'warn',
  'temporal/workflow-prefer-single-object-args': 'warn',
  'temporal/workflow-require-handler-serialization-safe-types': 'warn',
  'temporal/workflow-prefer-workflow-uuid': 'error',
  'temporal/workflow-no-floating-promises': 'error',
  'temporal/workflow-no-throw-raw-error': 'warn',
  'temporal/workflow-patch-id-literal': 'warn',
};
