import type { TSESLint } from '@typescript-eslint/utils';

/**
 * Workflow config - strict determinism rules for workflow files
 */
export const workflowRules: TSESLint.FlatConfig.Rules = {
  'temporal/workflow-condition-timeout-style': 'warn',
  'temporal/workflow-no-activity-definitions-import': 'error',
  'temporal/workflow-duration-format': 'warn',
  'temporal/workflow-activity-timeout-duration-format': 'warn',
  'temporal/workflow-require-message-definitions-at-module-scope': 'warn',
  'temporal/workflow-patched-must-guard-incompatible-change': 'warn',
  'temporal/workflow-require-deprecate-patch-after-branch-removal': 'warn',
  'temporal/workflow-replay-testing-required-comment': 'warn',
  'temporal/workflow-prefer-cancellation-scope-with-timeout': 'warn',
  'temporal/workflow-no-settimeout-in-cancellation-scope': 'warn',
  'temporal/workflow-no-swallow-cancellation': 'warn',
  'temporal/workflow-non-cancellable-cleanup-required': 'warn',
  'temporal/workflow-await-cancel-requested-in-non-cancellable-pattern': 'warn',
  'temporal/workflow-no-await-in-handler-without-exit-guard': 'warn',
  'temporal/workflow-no-fs-in-workflow': 'error',
  'temporal/workflow-no-node-or-dom-imports': 'error',
  'temporal/workflow-no-network-in-workflow': 'error',
  'temporal/workflow-no-logger-library-in-workflow': 'error',
  'temporal/workflow-no-uuid-library-in-workflow': 'error',
  'temporal/workflow-no-mixed-scope-exports': 'error',
  'temporal/workflow-no-top-level-workflow-side-effects': 'error',
  'temporal/workflow-no-unsafe-package-imports': 'error',
  'temporal/workflow-no-nondeterministic-control-flow': 'warn',
  'temporal/workflow-no-workflow-prng-for-persisted-ids': 'warn',
  'temporal/workflow-no-assert-in-production-workflow': 'warn',
  'temporal/workflow-no-date-now-tight-loop': 'warn',
  'temporal/workflow-no-wall-clock-assumptions': 'warn',
  'temporal/workflow-uuid4-requires-security-comment': 'warn',
  'temporal/workflow-no-heavy-cpu-in-workflow': 'warn',
  'temporal/workflow-no-large-literal-activity-payloads': 'warn',
  'temporal/workflow-no-large-literal-payloads': 'warn',
  'temporal/workflow-no-large-inline-constants': 'warn',
  'temporal/workflow-local-activity-options-required': 'error',
  'temporal/workflow-no-nonserializable-types-in-payloads': 'warn',
  'temporal/workflow-no-error-as-payload': 'warn',
  'temporal/workflow-no-bigint-in-payload': 'warn',
  'temporal/workflow-no-date-object-in-payload': 'warn',
  'temporal/workflow-require-explicit-payload-types': 'warn',
  'temporal/workflow-no-any-in-workflow-public-api': 'warn',
  'temporal/workflow-no-console': 'error',
  'temporal/workflow-no-continue-as-new-without-state-argument': 'warn',
  'temporal/workflow-require-activity-timeouts': 'error',
  'temporal/workflow-no-retry-for-nonidempotent-activities': 'warn',
  'temporal/workflow-require-idempotency-key-arg': 'warn',
  'temporal/workflow-prefer-single-object-args': 'warn',
  'temporal/workflow-prefer-local-activity-for-nondeterministic-value': 'warn',
  'temporal/workflow-require-handler-serialization-safe-types': 'warn',
  'temporal/workflow-prefer-workflow-uuid': 'error',
  'temporal/workflow-no-floating-promises': 'error',
  'temporal/workflow-no-frequent-search-attribute-upserts': 'warn',
  'temporal/workflow-no-throw-raw-error': 'warn',
  'temporal/workflow-patch-id-literal': 'warn',
  'temporal/workflow-search-attributes-upsert-shape': 'warn',
  'temporal/workflow-sink-args-must-be-cloneable': 'warn',
};
